web: uvicorn app.main:app --uds /var/run/cabotage/cabotage.sock --workers 1
web-test: uvicorn app.main:app --uds /var/run/cabotage/cabotage.sock --workers 1
worker: python -m app.worker
release: sh -c 'if [ -n "$DATABASE_URL" ]; then alembic upgrade head; fi'
job-chit-chat: env SCHEDULE="* * * * *" python chit-chat.py
